# Generated by Django 3.2.4 on 2021-07-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
