# Generated by Django 3.2.4 on 2021-07-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_other_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='skill_name',
        ),
    ]
