# Generated by Django 3.2.4 on 2021-07-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_skill_name_skills_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'skills'},
        ),
    ]
